### ISSUE TITLE
Blackfire profiling

### ISSUE THREAD

**Issue by fbourigault** [php-serializers/ivory-serializer-benchmark#14]
Before the PHPBench switch, I used the following command line to get blackfire.io profiles:

`blackfire run bin/benchmark --iteration 3 --horizontal-complexity 60 --vertical-complexity 60`

I currently have `vendor/bin/phpbench run --report=bench --filter=SymfonyObject --php-wrapper='blackfire run -q' --iterations 1 --revs 3 --parameters='[60,60]'` but this generates more than one profile.

How can I achieve proper profiling?

**Comment by fbourigault** [comment]
I started to write a PHPBench extension to use blackfire.io.

**Comment by tsantos84** [comment]
Hi @fbourigault, take a look at https://github.com/tsantos84/serializer-benchmark. You can find some useful content there. If you want, we can work to together on this. :)

**Comment by fbourigault** [comment]
I created an extension for PHPBench. It's in early stage, but I can get profiles on blackfire.io.

https://github.com/fbourigault/phpbench-blackfire-extension

You can try it by creating a `phpbench.json` from `phpbench.json.dist` and by adding the following lines to configuration:
```json
    "extension_autoloader": "/Users/fabien/Projets/fbourigault/phpbench-blackfire-extension/vendor/autoload.php",
    "extensions": [
        "Fbourigault\\PhpBench\\Extension\\Blackfire\\BlackfireExtension"
    ]
```

Then to profile the benchmark:
```
vendor/bin/phpbench blackfire:profile --filter=SymfonyObject --revs=3 --parameters='[1,1]'
```
